/* Generated by bin2c, do not edit manually */
#ifndef __mm_sound_h_included
#define __mm_sound_h_included

extern const long int all_sound_size;
extern const unsigned char all_sound[36992];

#endif    /* __mm_sound_h_included */
